<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="bec01eee36f06be"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Fahad Shah"
		rxversion="8.0.0.0"
		host="HUAWEI LUA-U22 (Unknown)
WLAN - 192.168.3.11"
		osversion="-"
		runtimeversion="-"
		procarch="-"
		oslanguage="-"
		dtnlanguage="-"
		screenresolution="-"
		timestamp="2/21/2018 3:56:10 PM"
		timestampiso="2018-02-21T10:56:10"
		endtime="2/21/2018 3:58:58 PM"
		timeoutfactor="1"
		module="AvailabilityCheck">
		<detail>
			AvailabilityCheck
		</detail>
		<errormessage>
			Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
		</errormessage>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="02:45.223"
			timeRelativeToTestModuleStartTime="02:45.223"
			timeWallClock="15:58:55"
			time="02:45.223"
			level="Error"
			category="Module"
			errimg=".\Availabi_d5c9d5be_edbb560d_trace.jpg"
			errthumb=".\Availabi_d5c9d5be_edbb560d_trace_thumb.jpg">
			<message>
				Index was out of range. Must be non-negative and less than the size of the collection.<br/>Parameter name: index
			</message>
			<metainfo
				stacktrace="   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at TradeTrackerProject.ConstantUserCode.UserCodeCollection.visitAvailabilityCheck() in d:\QA Automation\TradeTrackerProject\TradeTrackerProject\UserCodeCollection\UserCodeCollection.cs:line 470
   at TradeTrackerProject.TestCases.TK_ShopOpen.AvailabilityCheck.Ranorex.Core.Testing.ITestModule.Run() in d:\QA Automation\TradeTrackerProject\TradeTrackerProject\TestCases\TK ShopOpen\AvailabilityCheck.cs:line 82
   at Ranorex.Core.Testing.TestModuleLeaf.RunInternal(DataContext parentDataContext, Int32 iteration, Int32 iterationCount, Boolean skipIteration)"
				codefile="d:\QA Automation\TradeTrackerProject\TradeTrackerProject\UserCodeCollection\UserCodeCollection.cs"
				codeline="470"
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
